import pandas as pd
import streamlit as st

from app.controller import hedger_v2_controller as ctrl
from app.vue.components.page_utils import render_page_header

TAB_LABEL = "🛡️ Hedging Systems"


def _render_pill(title: str, body: str, tone: str = "info") -> None:
    gradients = {
        "info": ("#5ac8fa", "#7c83ff"),
        "success": ("#34d399", "#22d3ee"),
        "warn": ("#fbbf24", "#f97316"),
    }
    c1, c2 = gradients.get(tone, gradients["info"])
    html = f"""
    <div style="
        background: linear-gradient(135deg, {c1}, {c2});
        color: #f8fafc;
        padding: 12px 14px;
        border-radius: 14px;
        box-shadow: 0 10px 30px rgba(0,0,0,0.25);
        border: 1px solid rgba(255,255,255,0.12);
        margin: 8px 0;
    ">
        <div style="font-weight: 700; font-size: 0.95rem; letter-spacing: 0.01em; margin-bottom: 4px;">
            {title}
        </div>
        <div style="font-size: 0.85rem; opacity: 0.95;">{body}</div>
    </div>
    """
    st.markdown(html, unsafe_allow_html=True)


def _format_suggestion_text(ref: str, suggestion: dict) -> str:
    side = str(suggestion.get("side") or "").lower()
    delta = float(suggestion.get("delta_qty", 0.0) or 0.0)
    action = "Buy" if side == "buy" else "Sell"
    qty_str = f"{delta:.2f}".rstrip("0").rstrip(".") if delta else "0"
    comment = suggestion.get("comment") or "Generated by DQN hedge prototype."
    return (
        f"{action} about {qty_str} contracts/shares to rebalance exposure for {ref}. "
        f"Note: {comment}"
    )


def _format_execution_text(ref: str, result: dict | str) -> str:
    if isinstance(result, dict):
        status = result.get("status") or result.get("message") or "sent"
        qty = result.get("qty") or result.get("quantity")
        side = str(result.get("side") or "").lower()
        action = "buy" if side == "buy" else "sell" if side else "trade"
        qty_part = f"{qty}" if qty is not None else "order"
        return f"Hedge {action} {qty_part} for {ref} {status}."
    return f"Hedge request for {ref}: {result}"


def _render_pill(title: str, body: str, tone: str = "info") -> None:
    gradients = {
        "info": ("#5ac8fa", "#7c83ff"),
        "success": ("#34d399", "#22d3ee"),
        "warn": ("#fbbf24", "#f97316"),
        "error": ("#f43f5e", "#ef4444"),
    }
    c1, c2 = gradients.get(tone, gradients["info"])
    html = f"""
    <div style="
        background: linear-gradient(135deg, {c1}, {c2});
        color: #f8fafc;
        padding: 12px 14px;
        border-radius: 14px;
        box-shadow: 0 10px 30px rgba(0,0,0,0.25);
        border: 1px solid rgba(255,255,255,0.12);
        margin: 8px 0;
    ">
        <div style="font-weight: 700; font-size: 0.95rem; letter-spacing: 0.01em; margin-bottom: 4px;">
            {title}
        </div>
        <div style="font-size: 0.85rem; opacity: 0.95;">{body}</div>
    </div>
    """
    st.markdown(html, unsafe_allow_html=True)


def _render_account() -> None:
    return


def _render_positions() -> list[dict]:
    st.markdown("### Positions (actions & options)")
    equities = ctrl.get_equity_positions()
    options = ctrl.get_option_positions()

    if not equities and not options:
        st.info("No Alpaca positions.")
        return []

    if equities:
        st.caption("Equity positions")
        st.dataframe(pd.DataFrame(equities), hide_index=True, width="stretch")

    if options:
        st.caption("Option positions")
        st.dataframe(pd.DataFrame(options), hide_index=True, width="stretch")

    return options or []


def _render_dqn_panel(option_positions: list[dict]) -> None:
    st.markdown("### Panneau de couverture (DQN)")

    with st.expander("Modèle DQN (statut & entraînement)", expanded=False):
        status = ctrl.get_dqn_model_status()
        weights_ok = bool(status.get("weights_exists"))
        if weights_ok:
            st.success("Modèle DQN trouvé (cache).")
        else:
            st.warning("Aucun modèle DQN en cache. Entraîne-le une première fois.")

        meta = status.get("meta") or {}
        trained_utc = meta.get("trained_utc") or meta.get("loaded_utc") or "n/a"
        meta_cfg = meta.get("config", {}) or {}
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Version", str(status.get("version", "n/a")))
        c2.metric("Trained/Loaded (UTC)", str(trained_utc))
        c3.metric("Eval |abs(delta)|", f"{(meta.get('eval_avg_abs_total_delta') or 0.0):.3f}")
        c4.metric("Train avg loss", f"{(meta.get('train_avg_loss') or 0.0):.6f}")
        st.caption("Mode d'entraînement : historical (prix Alpaca) — nécessite des credentials valides.")

        train_steps = st.slider(
            "Train steps",
            min_value=500,
            max_value=25_000,
            value=int((meta.get("train_steps") or 7_500)),
            step=250,
        )
        seed = st.number_input("Seed", min_value=0, value=int(meta_cfg.get("seed", 42)), step=1)

        hist_symbol = meta_cfg.get("historical_symbol", "SPY")
        hist_lookback = int(meta_cfg.get("historical_lookback_days", 180) or 180)
        hist_lookback = min(max(hist_lookback, 30), 365)
        hist_episode_len = int(meta_cfg.get("historical_episode_length", 64) or 64)
        hist_episode_len = min(max(hist_episode_len, 8), 256)
        hist_timeframe = str(meta_cfg.get("historical_timeframe", "1Day"))

        st.info("Le mode historical requiert des credentials Alpaca valides pour télécharger les prix.")
        col_h1, col_h2 = st.columns(2)
        hist_symbol = col_h1.text_input("Ticker (historique)", value=str(hist_symbol).upper())
        hist_timeframe = col_h2.selectbox("Timeframe Alpaca", options=["1Day", "1Hour", "1Min"], index=0)
        hist_lookback = st.slider("Lookback (jours)", min_value=30, max_value=365, value=hist_lookback, step=15)
        hist_episode_len = st.slider("Longueur épisode (pas)", min_value=8, max_value=256, value=hist_episode_len, step=8)

        force_retrain = st.checkbox("Force retrain (overwrite cache)", value=False)
        if st.button("Train / update DQN", type="primary"):
            try:
                with st.spinner("Training DQN (numpy)..."):
                    meta_out = ctrl.train_dqn_model(
                        train_steps=int(train_steps),
                        seed=int(seed),
                        force_retrain=bool(force_retrain),
                        historical_symbol=hist_symbol,
                        historical_timeframe=hist_timeframe,
                        historical_lookback_days=int(hist_lookback),
                        historical_episode_length=int(hist_episode_len),
                    )
            except Exception as exc:
                st.error(f"Échec de l'entraînement DQN: {exc}")
            else:
                st.success("DQN entraîné et sauvegardé.")
                with st.expander("Détails (meta)", expanded=False):
                    st.json(meta_out)

    if option_positions:
        choices = [
            f"{pos.get('symbol', '')} | {pos.get('side', '')} {pos.get('qty', '')}"
            for pos in option_positions
        ]
        selected_label = st.selectbox("Option à couvrir", choices)
        try:
            idx = choices.index(selected_label)
        except ValueError:
            idx = 0
        option_symbol = str(option_positions[idx].get("symbol", "")).upper()
        mode = "option"
    else:
        st.info("Aucune position option détectée. Entre un underlying pour tester le hedger.")
        option_symbol = ""
        underlying_symbol = st.text_input("Underlying symbol", placeholder="AAPL").upper()
        mode = "underlying"

    status = ctrl.get_status()
    ready = bool(status.get("ready"))
    offline = bool(status.get("offline"))
    if not ready:
        st.warning("Alpaca client offline ou credentials manquantes : les ordres seront bloqués.")

    b1, b2 = st.columns(2)

    with b1:
        if st.button("Get DQN hedge suggestion"):
            try:
                if mode == "option":
                    suggestion = ctrl.get_dqn_hedge_suggestion_for_option(option_symbol)
                    ref = option_symbol
                else:
                    suggestion = ctrl.get_dqn_hedge_suggestion(underlying_symbol)
                    ref = underlying_symbol

                _render_pill(
                    f"Suggestion for {ref}",
                    _format_suggestion_text(ref, suggestion),
                    tone="info",
                )
                with st.expander("Détails (Q-values / state)", expanded=False):
                    st.write({"q_values": suggestion.get("q_values"), "state": suggestion.get("state")})
            except Exception as exc:
                st.error(f"Failed to get suggestion: {exc}")

    with b2:
        if st.button("Execute DQN hedge on Alpaca", disabled=not ready):
            try:
                if mode == "option":
                    result = ctrl.execute_dqn_hedge_for_option(option_symbol)
                    ref = option_symbol
                else:
                    result = ctrl.execute_dqn_hedge(underlying_symbol)
                    ref = underlying_symbol
                tone = "success"
                msg = _format_execution_text(ref, result)
                if isinstance(result, dict) and str(result.get("status", "")).lower() == "error":
                    tone = "error"
                _render_pill(
                    f"Executed hedge for {ref}",
                    msg,
                    tone=tone,
                )
            except Exception as exc:
                st.error(f"Hedge execution failed: {exc}")

    st.caption(
        "DQN v3 (numpy): replay buffer + target network, entraîné uniquement sur des prix historiques Alpaca."
    )

    # Automatic pass: hedge all underlyings present in the option portfolio
    st.markdown("### Couverture automatique (options en portefeuille)")
    underlyings = ctrl.get_option_underlyings()
    if not underlyings:
        st.info("Aucune option détectée dans le portefeuille.")
    else:
        col_auto_sugg, col_auto_exec = st.columns(2)
        auto_results = []
        if col_auto_sugg.button("Suggestions pour toutes les options"):
            try:
                auto_results = ctrl.get_portfolio_option_hedges(execute=False)
            except Exception as exc:
                st.error(f"Impossible d'obtenir les suggestions: {exc}")
        if col_auto_exec.button("Exécuter les hedges (toutes)", disabled=not ready):
            try:
                auto_results = ctrl.get_portfolio_option_hedges(execute=True)
            except Exception as exc:
                st.error(f"Exécution des hedges impossible: {exc}")

        for res in auto_results or []:
            u = res.get("underlying", "")
            suggestion = res.get("suggestion", {})
            order = res.get("order")
            _render_pill(
                f"Hedge pour {u or 'n/a'}",
                _format_suggestion_text(u, suggestion),
                tone="info",
            )
            if order:
                tone = "success"
                body = _format_execution_text(u, order)
                if isinstance(order, dict) and str(order.get("status", "")).lower() == "error":
                    tone = "error"
                _render_pill(
                    f"Ordre exécuté pour {u or 'n/a'}",
                    body,
                    tone=tone,
                )
            else:
                _render_pill(
                    f"Ordre exécuté pour {u or 'n/a'}",
                    "Aucun ordre exécuté ou execution non demandée.",
                    tone="warn",
                )


def render_tab() -> None:
    render_page_header(
        "Hedging Systems (Alpaca)",
        "Couverture options: suggestions DQN (prototype) et exécution via Alpaca.",
        icon="🛡️",
        badge="Hedging",
    )

    # Positions shown read-only
    option_positions = _render_positions()

    st.divider()
    _render_dqn_panel(option_positions)


def render() -> None:
    render_tab()
