"""D2.f — floating-strike lookback (app/model/options/core/pricing_lib.py).

`view_lookback` had no pricing model at all: its premium was the intrinsic payoff
evaluated at the reference spot,

    premium = payoff_lookback_floating(spot_ref, min_path, max_path, ...)

so the option carried zero time value, and the `T` and `k_ref` arguments were accepted
then ignored. `view_lookback_fixed` went further and filled the whole payoff grid with
that same constant, making its P&L identically zero on every spot.

This pins a real Goldman-Sosin-Gatto pricer.

ORACLES:
1. QUANTITATIVE: Monte-Carlo on the actual path extremum, with the Broadie-Glasserman-Kou
   continuity correction (a discretely monitored extremum is biased towards the spot by
   exp(-/+ beta*sigma*sqrt(dt)), beta = 0.5826) so a discrete simulation can be compared
   with a continuously monitored closed form.
2. MODEL-FREE, EXACT: at T = 0 the price is the intrinsic payoff, and it is always at
   least the intrinsic (the holder can wait) — the old "premium = payoff" satisfied the
   first and turned the second into an equality everywhere, which is the defect.
3. MODEL-FREE: a lookback call dominates the vanilla ATM call struck at the running
   minimum, because S_T - min >= (S_T - min)^+ ... with equality of payoffs only when
   the option finishes above the running minimum, which a lookback always does.
4. MONOTONICITY: worth more the longer it runs, and more when the running extremum is
   further from spot.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from app.model.options.core.pricing_lib import price_lookback_floating

pytestmark = pytest.mark.unit

BGK_BETA = 0.5826  # Broadie-Glasserman-Kou continuity correction constant


def _mc_lookback(S, extremum, r, q, sigma, T, option_type, n_paths=60_000, n_steps=2000, seed=5):
    """MC on the running extremum, corrected for discrete monitoring."""
    rng = np.random.default_rng(seed)
    dt = T / n_steps
    shift = math.exp(BGK_BETA * sigma * math.sqrt(dt))
    drift = (r - q - 0.5 * sigma * sigma) * dt
    vol = sigma * math.sqrt(dt)

    s = np.full(n_paths, float(S))
    running = np.full(n_paths, float(extremum))
    for _ in range(n_steps):
        s = s * np.exp(drift + vol * rng.standard_normal(n_paths))
        if option_type == "call":
            np.minimum(running, s, out=running)
        else:
            np.maximum(running, s, out=running)
    # continuity correction applies to the part of the extremum generated by the path
    if option_type == "call":
        corrected = np.minimum(running / shift, float(extremum))
        payoff = s - corrected
    else:
        corrected = np.maximum(running * shift, float(extremum))
        payoff = corrected - s
    disc = payoff * math.exp(-r * T)
    return float(np.mean(disc)), float(np.std(disc, ddof=1) / math.sqrt(n_paths))


# (S, extremum, r, q, sigma, T)  — extremum is the running min for a call, max for a put
CALL_CASES = [
    (100.0, 100.0, 0.05, 0.00, 0.25, 1.0),  # fresh start
    (100.0, 85.0, 0.05, 0.02, 0.30, 1.0),  # seasoned: min already well below spot
    (100.0, 98.0, 0.03, 0.01, 0.20, 0.5),
]
PUT_CASES = [
    (100.0, 100.0, 0.05, 0.00, 0.25, 1.0),
    (100.0, 120.0, 0.05, 0.02, 0.30, 1.0),
    (100.0, 103.0, 0.03, 0.01, 0.20, 0.5),
]
_CIDS = [f"S{s:g}-m{m:g}-r{r:g}-q{q:g}-sig{v:g}-T{t:g}" for s, m, r, q, v, t in CALL_CASES]
_PIDS = [f"S{s:g}-M{m:g}-r{r:g}-q{q:g}-sig{v:g}-T{t:g}" for s, m, r, q, v, t in PUT_CASES]


@pytest.mark.parametrize(("S", "m", "r", "q", "sigma", "T"), CALL_CASES, ids=_CIDS)
def test_lookback_call_matches_monte_carlo(S, m, r, q, sigma, T):
    mc, stderr = _mc_lookback(S, m, r, q, sigma, T, "call")
    got = price_lookback_floating(S, m, r=r, q=q, sigma=sigma, T=T, option_type="call")
    tol = 3.0 * stderr + 0.004 * mc  # MC noise + residual discretisation
    assert got == pytest.approx(mc, abs=tol), f"{got:.4f} vs MC {mc:.4f} +/- {stderr:.4f}"


@pytest.mark.parametrize(("S", "M", "r", "q", "sigma", "T"), PUT_CASES, ids=_PIDS)
def test_lookback_put_matches_monte_carlo(S, M, r, q, sigma, T):
    mc, stderr = _mc_lookback(S, M, r, q, sigma, T, "put")
    got = price_lookback_floating(S, M, r=r, q=q, sigma=sigma, T=T, option_type="put")
    tol = 3.0 * stderr + 0.004 * mc
    assert got == pytest.approx(mc, abs=tol), f"{got:.4f} vs MC {mc:.4f} +/- {stderr:.4f}"


@pytest.mark.parametrize(("S", "m", "r", "q", "sigma", "_T"), CALL_CASES, ids=_CIDS)
def test_zero_maturity_is_the_intrinsic(S, m, r, q, sigma, _T):
    got = price_lookback_floating(S, m, r=r, q=q, sigma=sigma, T=0.0, option_type="call")
    assert got == pytest.approx(S - m, abs=1e-12)


@pytest.mark.parametrize(("S", "m", "r", "q", "sigma", "T"), CALL_CASES, ids=_CIDS)
def test_lookback_is_strictly_above_its_intrinsic_while_alive(S, m, r, q, sigma, T):
    """The old code returned exactly the intrinsic — no time value at all."""
    got = price_lookback_floating(S, m, r=r, q=q, sigma=sigma, T=T, option_type="call")
    assert got > (S - m) + 1e-6, f"{got:.6f} vs intrinsic {S - m:.6f}"


@pytest.mark.parametrize(("S", "m", "r", "q", "sigma", "_T"), CALL_CASES, ids=_CIDS)
def test_value_grows_with_maturity(S, m, r, q, sigma, _T):
    values = [
        price_lookback_floating(S, m, r=r, q=q, sigma=sigma, T=t, option_type="call")
        for t in (0.25, 0.5, 1.0, 2.0)
    ]
    assert all(b > a for a, b in zip(values, values[1:])), values


def test_value_grows_as_the_running_minimum_falls():
    kw = dict(r=0.05, q=0.0, sigma=0.25, T=1.0, option_type="call")
    values = [price_lookback_floating(100.0, m, **kw) for m in (100.0, 95.0, 90.0, 80.0)]
    assert all(b > a for a, b in zip(values, values[1:])), values


def test_zero_drift_case_is_finite():
    """b = r - q = 0 makes the sigma^2/(2b) term singular — it must still return a number."""
    got = price_lookback_floating(100.0, 100.0, r=0.03, q=0.03, sigma=0.25, T=1.0,
                                  option_type="call")
    assert math.isfinite(got) and got > 0.0
    mc, stderr = _mc_lookback(100.0, 100.0, 0.03, 0.03, 0.25, 1.0, "call")
    assert got == pytest.approx(mc, abs=3.0 * stderr + 0.004 * mc)
